### ISSUE TITLE
CelebHQ checkpoint

### ISSUE THREAD

**Issue by nitba** [XuezheMax/wolf#2]
Hi @XuezheMax ,

Thanks for your nice works,
for the "MaCow" paper, would you please share checkpoints for "CelebHQ dataset"?
to have "Celeb-HQ" images, I have used "CelebAMask-HQ" dataset  which has 2993 validation and 2824 test samples. is that correct?

**Comment by XuezheMax** [comment]
Hi @abelfz 

I have the checkpoints for the "decoupled" paper, but not those for the "MaCow" paper.
For the CelebA-HQ dataset, it contains totally 30000 samples and I split to 27000/3000 for training and validation.

**Comment by nitba** [comment]
@XuezheMax 
Sorry, I feel a bit confused on the dataset, since I split "CelebAMask-HQ" dataset according to the instructions,
I have checked previous SOTA  on "Celeb-HQ", they shared dataset in tf-records formats (find it hard to check ids). 
Would you please share the dataset (or val ids) ?

**Comment by XuezheMax** [comment]
For the CelebA-HQ, I also used the tf-records to extract the images.
